# Generated by Django 5.1.6 on 2025-02-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('contato', models.CharField(max_length=15, verbose_name='contato do fornecedor')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='cnpj')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedor',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Categoria do Produto'),
        ),
    ]
