# Generated by Django 5.1.6 on 2025-03-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criadoEm',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
